name: Run GitHub Backup

on:
    push:
        branches: ["main"]
        paths:
            - "GitHub Backup/**"
            - ".github/workflows/backup.yml"
    schedule:
        - cron: "0 0 * * 5"

env:
    AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
    BASE_DIR: ${{ secrets.BASE_DIR }}
    TF_VAR_github_token: ${{ secrets.AUTH_TOKEN }}
    TF_VAR_aws_bucket_name: ${{ secrets.AWS_BUCKET_NAME }}
    TF_VAR_aws_bucket_region: ${{ secrets.AWS_BUCKET_REGION }}
    TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
    TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
    TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
    TF_VAR_aws_region_az: ${{ secrets.AWS_REGION_AZ }}
    TF_INPUT: 0

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                  terraform_version: 1.3.9
            - name: Terraform Init
              working-directory: GitHub Backup/terraform
              run: terraform init
            - name: Terraform Plan
              working-directory: GitHub Backup/terraform
              run: terraform plan -out=plan
            - name: Terraform Apply
              working-directory: GitHub Backup/terraform
              run: terraform apply -state=plan -input=false
            - name: Sleep
              run: sleep 2h
            - name: Terraform Destroy
              working-directory: GitHub Backup/terraform
              run: terraform destroy -auto-approve
